getting unexpected results from python 3.12

diff --git a/.github/workflows/update-docs.yml b/.github/workflows/update-docs.yml
--- a/.github/workflows/update-docs.yml
+++ b/.github/workflows/update-docs.yml
@@ -24,23 +24,24 @@ jobs:
         conda env update --file docs-environment.yml --name base
     - name: Build documentation
       run: |
+        conda activate base
         python build_docs.py
-    # Publish built docs
-    # ===============================
-    - name: Commit documentation changes
-      run: |
-        cd docs
-        touch .nojekyll
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        directory: docs
-        github_token: ${{ secrets.GITHUB_TOKEN }}
-    # ===============================
+    # # Publish built docs
+    # # ===============================
+    # - name: Commit documentation changes
+    #   run: |
+    #     cd docs
+    #     touch .nojekyll
+    #     git config --local user.email "action@github.com"
+    #     git config --local user.name "GitHub Action"
+    #     git add .
+    #     git commit -m "Update documentation" -a || true
+    #     # The above command will fail if no changes were present, so we ignore
+    #     # that.
+    # - name: Push changes
+    #   uses: ad-m/github-push-action@master
+    #   with:
+    #     directory: docs
+    #     github_token: ${{ secrets.GITHUB_TOKEN }}
+    # # ===============================
   
